  version: '3'

  services:
    web:
      image: python-flask-app1
      ports:
        - "5001:5000"
      restart: always
      environment:
        - FLASK_APP=main.py
        - FLASK_ENV=production

    db:
      image: mysql:5.7  # Use a specific MySQL version
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=test@123
